### ISSUE TITLE
Support for ES2015 module exports

### ISSUE THREAD

**Issue by jgornick** [bodia-uz/odata-filter-builder#12]
Providing only default exports from a module doesn't play well with other module systems. Would it be possible to also export the ODataFilterBuilder as a named export so one might import like:

```typescript
import { ODataFilterBuilder } from 'odata-filter-builder';
```

I currently use webpack with a module system of es2015 and target es5. In order to make TypeScript play well with the module, I had to change the export in index.d.ts to:

```typescript
declare var ODataFilterBuilder: ODataFilterBuilderStatic;
export = ODataFilterBuilder;
```

and import like:

```typescript
import * as ODataFilterBuilder from 'odata-filter-builder';
```

If I don't do that, TypeScript complains with: 

```
Cannot invoke an expression whose type lacks a call signature...
```

... when trying to use the callable for the ODataFilterBuilder interface:

```typescript
ODataFilterBuilder('and').eq('foo', 'bar');
```

Other than that, great library!

**Comment by bodia-uz** [comment]
Hey @jgornick !
Glad you're using `ODataFilterBuilder`!

I will fix it soon.

Have You tried [esModuleInterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop) from typescript 2.7?
It should fix Your issue for now.
With this option your import should be:
```
import ODataFilterBuilder from 'odata-filter-builder';
```

**Comment by jgornick** [comment]
Nice! Haven't been able to upgrade yet to 2.7.x, but will give this a try when I can upgrade. If I have some time, I'll first look into providing a PR with the fix.

Thanks!

**Comment by bodia-uz** [comment]
Published version `1.0.0-0`

Could be installed via `npm install odata-filter-builder@next`

**Comment by bodia-uz** [comment]
With ts we have one more issue:
> TypeError: Class constructor ODataFilterBuilder cannot be invoked without 'new'

Mb will drop support of `ODataFilterBuilder` without `new`.

@jgornick what You think?

**Comment by jgornick** [comment]
Externally, sure it makes sense to not support a consumer creating a new instance of ODataFilterBuilder.

Another option would be to allow the creation of new instances and then having "static" methods to create a new instance of ODataFilterBuilder:

```typescript
const fb: ODataFilterBuilder = ODataFilterBuilder.and();

// or

const fb: ODataFilterBuilder = ODataFilterBuilder.or();
```

Thoughts?

**Comment by bodia-uz** [comment]
Static methods for creating (`and` and `or`) are already available
https://github.com/bodia-uz/odata-filter-builder/blob/v1.0.0-0/src/ODataFilterBuilder.js#L230-L231

But the documentation for them could be better.

Currently, doc says to use:
```
const fb: ODataFilterBuilder = ODataFilterBuilder();

fb.eq('x', 1);
```

Need to depracate old format and update doc with:
```
const fb: ODataFilterBuilder = new ODataFilterBuilder();
// or
const fb: ODataFilterBuilder = ODataFilterBuilder.and();
// or
const fb: ODataFilterBuilder = ODataFilterBuilder.or();

fb.eq('x', 1);
```

Or/And mb add factory functions to module export:
```
import { and, or } from "odata-filter-builder";
// import { createAnd, createOr } from "odata-filter-builder";

const fb: ODataFilterBuilder = and();
// or
const fb: ODataFilterBuilder = or();
```

**Comment by jgornick** [comment]
@bodia-uz This is looking awesome! I like the ability to just use `and()` or `or()` as factory methods. Awesome stuff!
