### ISSUE TITLE
How to send UID (eg 24221e2b-16e4-29b3-bb6c-bgb4fa724915) without quotes?

### ISSUE THREAD

**Issue by CoonJS** [bodia-uz/odata-filter-builder#17]

**Comment by CoonJS** [comment]
I want to send filter eg $filter=userId eq 4221e2b-16e4-29b3-bb6c-bgb4fa724915, but i can't, because your lib inserts quotes in String values. How to fix this?

**Comment by bodia-uz** [comment]
use third param in `eq` method:
```javascript
import ODataFilterBuilder from 'odata-filter-builder';

const filter = ODataFilterBuilder()
  .eq('userId', '4221e2b-16e4-29b3-bb6c-bgb4fa724915', false)
  .toString();
```

https://codesandbox.io/s/421o5333j4
