### ISSUE TITLE
SubstringOf

### ISSUE THREAD

**Issue by atatakobry** [bodia-uz/odata-filter-builder#6]
Please, can you implement a legacy functional for covering such command as substringof, etc.? Unfortunately, it's not always possible to use the latest oData on backend part. Thank you!

**Comment by bodia-uz** [comment]
We can add something like:
```js
ODataFilterBuilder.prototype.fn = function(fnName, field, values, normaliseValues, reverse) {...}

//examples
`f().fn('substringof', 'CompanyName', ['google'], true, true)`
// substringof('google', CompanyName)

`f().fn('substringof', x => x.toLower('CompanyName'), ['google'], true, true)`
// substringof('google', tolower(CompanyName))
```

Feel free to create PR.

See `functiions` implementation [here](https://github.com/bodia-uz/odata-filter-builder/blob/master/src/lib/canonicalFunctions.js#L4-L23)

**Comment by bodia-uz** [comment]
Or use existing functional
```js
f().eq('type', 1)._add("substringof('google', tolower(CompanyName))")
// "(type eq 1) and (substringof('google', tolower(CompanyName)))"
```
