### ISSUE TITLE
ODataV4 Datetime filters not supported

### ISSUE THREAD

**Issue by podgito** [bodia-uz/odata-filter-builder#8]
`filter.gt('eventDateTime', someDate, true)` doesn't produce a filter in the correct OData format. This applies to all filters, not just `filter.gt`. 

ODataV3-V4 datetime filters should be in the following format
(eventDateTime gt 2016-11-16T00:00:00Z) - ISO 8601 and no quotes

**Comment by bodia-uz** [comment]
Available in v0.2.0
